#!/bin/sh
# id 83c59ee7d6a4479c8e142422cbe9022a
# client secret 6d5c0077c6d4e214c6850d5f1611689e

curl -i -k --tlsv1 -H "Accept:application/json" -H "Content-Type:application/x-www-form-urlencoded" -X POST https://api-sandbox.capitalone.com/oauth2/token -d client_id=83c59ee7d6a4479c8e142422cbe9022a -d client_secret=6d5c0077c6d4e214c6850d5f1611689e -d grant_type=client_credentials


# {"issued_at":1534563549,"token_type":"Bearer","expires_in":1296000,"access_token":"eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwicGNrIjoxLCJhbGciOiJkaXIiLCJ0diI6Miwia2lkIjoicjRxIn0..CkTWn_gnlVUhdMtpRn1wzA.etgcOUfgJZ4bbHHwha-KFXq8WQb_d4nl48CapEUJKwIAjI0XgPihIlPJVSmqlW-k_ThQ8cc9c5FULFvjCURHRugBmdUvEukHShyozbMJNp2lAbrgfIM_ch07YRbdjMbhbB1_CZYmusDLRxaI9NFicV-TyUVNXDg71MEqXntAa8LBPkGtz9WMGHX331im72fSXQhCmBECYCPLL1veHoL3b3sHv_Zrx_JSS7b-GeK16WCBYaEKFWYS2z38gsFV1QGENJI4U05S4k_QToSrlBUqMCyRAHRWDpdDk6pL2jbyCUc.fClv_c9Cu3wfd4gvmuuvJA"}


curl -i -k --tlsv1 -H 'Accept: application/json;v=0' -H 'Authorization: Bearer eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwicGNrIjoxLCJhbGciOiJkaXIiLCJ0diI6Miwia2lkIjoicjRxIn0..CkTWn_gnlVUhdMtpRn1wzA.etgcOUfgJZ4bbHHwha-KFXq8WQb_d4nl48CapEUJKwIAjI0XgPihIlPJVSmqlW-k_ThQ8cc9c5FULFvjCURHRugBmdUvEukHShyozbMJNp2lAbrgfIM_ch07YRbdjMbhbB1_CZYmusDLRxaI9NFicV-TyUVNXDg71MEqXntAa8LBPkGtz9WMGHX331im72fSXQhCmBECYCPLL1veHoL3b3sHv_Zrx_JSS7b-GeK16WCBYaEKFWYS2z38gsFV1QGENJI4U05S4k_QToSrlBUqMCyRAHRWDpdDk6pL2jbyCUc.fClv_c9Cu3wfd4gvmuuvJA' -X GET https://api-sandbox.capitalone.com/money-movement/accounts

# {"accounts":[{"accountNickname":"My fav savings","bankName":"Capital One","productName":"360 Savings","lastFourAccountNumber":5678,"availableBalance":30012.01,"moneyMovementAccountReferenceId":"XFhWXJQOVdudjhONmdsOV7QpZE5Ba25ut5pa0N75jjoLJh=","moneyReceivingOptions":[{"transferType":"ACH","remainingTransactionlimit":10000,"transferDuration":2},{"transferType":"Internal"}],"moneySendingOptions":[{"transferType":"ACH","remainingTransactionlimit":5000,"transferDuration":2},{"transferType":"Internal"}]},{"accountNickname":"My fav checking","bankName":"Capital One","productName":"360 Checking","lastFourAccountNumber":1234,"availableBalance":40989.0,"moneyMovementAccountReferenceId":"YHGRB+zRxznmdsOV7QpZE5Ba25ut5nliF486mFhNgk=","moneyReceivingOptions":[{"transferType":"ACH","remainingTransactionlimit":10000,"transferDuration":2},{"transferType":"Internal"}],"moneySendingOptions":[{"transferType":"ACH","remainingTransactionlimit":5000,"transferDuration":2},{"transferType":"Internal"}]},{"accountNickname":"Bofa Checking","bankName":"Bank of America","lastFourAccountNumber":7896,"moneyMovementAccountReferenceId":"WQE+mwrgBYGUNYXLOolUO7MElxlcLAm2gtZJW2I6MeKC0=","moneyReceivingOptions":[{"transferType":"ACH","remainingTransactionlimit":10000,"transferDuration":2}],"moneySendingOptions":[{"transferType":"ACH","remainingTransactionlimit":2000,"transferDuration":2}]},{"accountNickname":"Chase Checking","bankName":"Chase","lastFourAccountNumber":2301,"moneyMovementAccountReferenceId":"CSE+xlcLAmgtZJQVdudjhmUO7M5ut5nliFOezJW2I6ZLD=","moneyReceivingOptions":[{"transferType":"ACH","remainingTransactionlimit":10000,"transferDuration":2}],"moneySendingOptions":[{"transferType":"ACH","remainingTransactionlimit":2000,"transferDuration":2}]}]}

